// <auto-generated />
using System;
using ByProxy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ByProxy.Migrations
{
    [DbContext(typeof(ProxyDb))]
    [Migration("20251121000523_v1.0.4")]
    partial class v104
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("AuthRoleUserEntity", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserEntityId")
                        .HasColumnType("TEXT");

                    b.HasKey("RolesId", "UserEntityId");

                    b.HasIndex("UserEntityId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("ByProxy.Models.AcmeAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Hidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AcmeAccounts");
                });

            modelBuilder.Entity("ByProxy.Models.AcmeCertHost", b =>
                {
                    b.Property<Guid>("CertificateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChallengeType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("CertificateId", "Host");

                    b.ToTable("AcmeHosts");

                    b.HasDiscriminator<string>("ChallengeType").HasValue("AcmeCertHost");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ByProxy.Models.AcmeDnsProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Draft")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Script")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AcmeDnsProviders");
                });

            modelBuilder.Entity("ByProxy.Models.AuthRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuthRoles");
                });

            modelBuilder.Entity("ByProxy.Models.AuthSession", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("UserId");

                    b.ToTable("AuthSessions");
                });

            modelBuilder.Entity("ByProxy.Models.ProxyCert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Hidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Certificates");

                    b.HasDiscriminator<string>("Type").HasValue("ProxyCert");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ByProxy.Models.ProxyCluster", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfigRevision")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AcceptAnyCert")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LoadBalancing")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("StickySessions")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id", "ConfigRevision");

                    b.HasIndex("ConfigRevision");

                    b.ToTable("Clusters");
                });

            modelBuilder.Entity("ByProxy.Models.ProxyConfig", b =>
                {
                    b.Property<int>("Revision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AdminCertId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AdminListenAny")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdminPort")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BasedOnRevision")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Committed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CommittedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfirmSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("FallbackCertId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReversionReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Reverted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Tarpit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnmatchedStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Revision");

                    b.HasIndex("AdminCertId");

                    b.HasIndex("FallbackCertId");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("ByProxy.Models.ProxyDestination", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfigRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ClusterConfigRevision")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ClusterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Health")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id", "ConfigRevision");

                    b.HasIndex("ConfigRevision");

                    b.HasIndex("ClusterId", "ClusterConfigRevision");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("ByProxy.Models.ProxyRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfigRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedHeaders")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClusterConfigRevision")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ClusterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hosts")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HttpPort")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HttpsPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Methods")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PathIsPrefix")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PreserveClientHeaders")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PreserveHostHeader")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RedirectLocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SuppressHttpsRedirect")
                        .HasColumnType("INTEGER");

                    b.Property<string>("XForwardedForAction")
                        .HasColumnType("TEXT");

                    b.Property<string>("XForwardedHostAction")
                        .HasColumnType("TEXT");

                    b.Property<string>("XForwardedPrefix")
                        .HasColumnType("TEXT");

                    b.Property<string>("XForwardedPrefixAction")
                        .HasColumnType("TEXT");

                    b.Property<string>("XForwardedProtoAction")
                        .HasColumnType("TEXT");

                    b.HasKey("Id", "ConfigRevision");

                    b.HasIndex("ConfigRevision");

                    b.HasIndex("ClusterId", "ClusterConfigRevision");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("ByProxy.Models.ProxyRouteMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfigRevision")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CaseSensitiveValues")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RouteConfigRevision")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<string>("Values")
                        .HasColumnType("TEXT");

                    b.HasKey("Id", "ConfigRevision");

                    b.HasIndex("ConfigRevision");

                    b.HasIndex("RouteId", "RouteConfigRevision");

                    b.ToTable("MatchCriteria");

                    b.HasDiscriminator<string>("Type").HasValue("ProxyRouteMatch");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ByProxy.Models.ProxyRouteTransform", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfigRevision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RouteConfigRevision")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.HasKey("Id", "ConfigRevision");

                    b.HasIndex("ConfigRevision");

                    b.HasIndex("RouteId", "RouteConfigRevision");

                    b.ToTable("RouteTransforms");

                    b.HasDiscriminator<string>("Type").HasValue("ProxyRouteTransform");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ByProxy.Models.ProxySniMap", b =>
                {
                    b.Property<string>("Host")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfigRevision")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CertificateId")
                        .HasColumnType("TEXT");

                    b.HasKey("Host", "ConfigRevision");

                    b.HasIndex("CertificateId");

                    b.HasIndex("ConfigRevision");

                    b.ToTable("SniMaps");
                });

            modelBuilder.Entity("ByProxy.Models.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Culture")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PasswordLastSet")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PasswordResetRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreferredTheme")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Xml")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("ByProxy.Models.AcmeDnsCertHost", b =>
                {
                    b.HasBaseType("ByProxy.Models.AcmeCertHost");

                    b.Property<Guid>("DnsProviderId")
                        .HasColumnType("TEXT");

                    b.HasIndex("DnsProviderId");

                    b.HasDiscriminator().HasValue("dns-01");
                });

            modelBuilder.Entity("ByProxy.Models.AcmeHttpCertHost", b =>
                {
                    b.HasBaseType("ByProxy.Models.AcmeCertHost");

                    b.HasDiscriminator().HasValue("http-01");
                });

            modelBuilder.Entity("ByProxy.Models.CACert", b =>
                {
                    b.HasBaseType("ByProxy.Models.ProxyCert");

                    b.HasDiscriminator().HasValue("CA");
                });

            modelBuilder.Entity("ByProxy.Models.ServerCert", b =>
                {
                    b.HasBaseType("ByProxy.Models.ProxyCert");

                    b.HasDiscriminator().HasValue("ServerCert");
                });

            modelBuilder.Entity("ByProxy.Models.ProxyRouteHeaderMatch", b =>
                {
                    b.HasBaseType("ByProxy.Models.ProxyRouteMatch");

                    b.Property<string>("HeaderMatchMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Header");
                });

            modelBuilder.Entity("ByProxy.Models.ProxyRouteQueryMatch", b =>
                {
                    b.HasBaseType("ByProxy.Models.ProxyRouteMatch");

                    b.Property<string>("QueryMatchMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Query");
                });

            modelBuilder.Entity("ByProxy.Models.ProxyRouteHeaderTransform", b =>
                {
                    b.HasBaseType("ByProxy.Models.ProxyRouteTransform");

                    b.Property<string>("HeaderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeaderOperation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeaderValue")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Header");
                });

            modelBuilder.Entity("ByProxy.Models.ProxyRouteMethodTransform", b =>
                {
                    b.HasBaseType("ByProxy.Models.ProxyRouteTransform");

                    b.Property<string>("FromHttpMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToHttpMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Method");
                });

            modelBuilder.Entity("ByProxy.Models.ProxyRoutePathTransform", b =>
                {
                    b.HasBaseType("ByProxy.Models.ProxyRouteTransform");

                    b.Property<string>("PathMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PathString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Path");
                });

            modelBuilder.Entity("ByProxy.Models.ProxyRouteQueryTransform", b =>
                {
                    b.HasBaseType("ByProxy.Models.ProxyRouteTransform");

                    b.Property<string>("QueryKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QueryOperation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QueryValue")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Query");
                });

            modelBuilder.Entity("ByProxy.Models.AcmeCert", b =>
                {
                    b.HasBaseType("ByProxy.Models.ServerCert");

                    b.Property<Guid>("AcmeAccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAttempt")
                        .HasColumnType("TEXT");

                    b.HasIndex("AcmeAccountId");

                    b.HasDiscriminator().HasValue("ACME");
                });

            modelBuilder.Entity("ByProxy.Models.ImportedCert", b =>
                {
                    b.HasBaseType("ByProxy.Models.ServerCert");

                    b.HasDiscriminator().HasValue("Imported");
                });

            modelBuilder.Entity("ByProxy.Models.IssuedCert", b =>
                {
                    b.HasBaseType("ByProxy.Models.ServerCert");

                    b.Property<Guid>("IssuingCAId")
                        .HasColumnType("TEXT");

                    b.HasIndex("IssuingCAId");

                    b.HasDiscriminator().HasValue("Issued");
                });

            modelBuilder.Entity("AuthRoleUserEntity", b =>
                {
                    b.HasOne("ByProxy.Models.AuthRole", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ByProxy.Models.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ByProxy.Models.AcmeCertHost", b =>
                {
                    b.HasOne("ByProxy.Models.AcmeCert", "Certificate")
                        .WithMany("Hosts")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certificate");
                });

            modelBuilder.Entity("ByProxy.Models.AuthSession", b =>
                {
                    b.HasOne("ByProxy.Models.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("ByProxy.Models.ProxyCluster", b =>
                {
                    b.HasOne("ByProxy.Models.ProxyConfig", "Config")
                        .WithMany("Clusters")
                        .HasForeignKey("ConfigRevision")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Config");
                });

            modelBuilder.Entity("ByProxy.Models.ProxyConfig", b =>
                {
                    b.HasOne("ByProxy.Models.ServerCert", "AdminCert")
                        .WithMany()
                        .HasForeignKey("AdminCertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ByProxy.Models.ServerCert", "FallbackCert")
                        .WithMany()
                        .HasForeignKey("FallbackCertId");

                    b.Navigation("AdminCert");

                    b.Navigation("FallbackCert");
                });

            modelBuilder.Entity("ByProxy.Models.ProxyDestination", b =>
                {
                    b.HasOne("ByProxy.Models.ProxyConfig", "Config")
                        .WithMany()
                        .HasForeignKey("ConfigRevision")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ByProxy.Models.ProxyCluster", "Cluster")
                        .WithMany("Destinations")
                        .HasForeignKey("ClusterId", "ClusterConfigRevision")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cluster");

                    b.Navigation("Config");
                });

            modelBuilder.Entity("ByProxy.Models.ProxyRoute", b =>
                {
                    b.HasOne("ByProxy.Models.ProxyConfig", "Config")
                        .WithMany("Routes")
                        .HasForeignKey("ConfigRevision")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ByProxy.Models.ProxyCluster", "Cluster")
                        .WithMany()
                        .HasForeignKey("ClusterId", "ClusterConfigRevision")
                        .OnDelete(DeleteBehavior.ClientNoAction);

                    b.Navigation("Cluster");

                    b.Navigation("Config");
                });

            modelBuilder.Entity("ByProxy.Models.ProxyRouteMatch", b =>
                {
                    b.HasOne("ByProxy.Models.ProxyConfig", "Config")
                        .WithMany()
                        .HasForeignKey("ConfigRevision")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ByProxy.Models.ProxyRoute", "Route")
                        .WithMany("MatchCriteria")
                        .HasForeignKey("RouteId", "RouteConfigRevision")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Config");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("ByProxy.Models.ProxyRouteTransform", b =>
                {
                    b.HasOne("ByProxy.Models.ProxyConfig", "Config")
                        .WithMany()
                        .HasForeignKey("ConfigRevision")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ByProxy.Models.ProxyRoute", "Route")
                        .WithMany("Transforms")
                        .HasForeignKey("RouteId", "RouteConfigRevision")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Config");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("ByProxy.Models.ProxySniMap", b =>
                {
                    b.HasOne("ByProxy.Models.ServerCert", "Certificate")
                        .WithMany()
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ByProxy.Models.ProxyConfig", "Config")
                        .WithMany("SniMaps")
                        .HasForeignKey("ConfigRevision")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certificate");

                    b.Navigation("Config");
                });

            modelBuilder.Entity("ByProxy.Models.AcmeDnsCertHost", b =>
                {
                    b.HasOne("ByProxy.Models.AcmeDnsProvider", "DnsProvider")
                        .WithMany()
                        .HasForeignKey("DnsProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DnsProvider");
                });

            modelBuilder.Entity("ByProxy.Models.AcmeCert", b =>
                {
                    b.HasOne("ByProxy.Models.AcmeAccount", "AcmeAccount")
                        .WithMany()
                        .HasForeignKey("AcmeAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcmeAccount");
                });

            modelBuilder.Entity("ByProxy.Models.IssuedCert", b =>
                {
                    b.HasOne("ByProxy.Models.CACert", "IssuingCA")
                        .WithMany()
                        .HasForeignKey("IssuingCAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IssuingCA");
                });

            modelBuilder.Entity("ByProxy.Models.ProxyCluster", b =>
                {
                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("ByProxy.Models.ProxyConfig", b =>
                {
                    b.Navigation("Clusters");

                    b.Navigation("Routes");

                    b.Navigation("SniMaps");
                });

            modelBuilder.Entity("ByProxy.Models.ProxyRoute", b =>
                {
                    b.Navigation("MatchCriteria");

                    b.Navigation("Transforms");
                });

            modelBuilder.Entity("ByProxy.Models.AcmeCert", b =>
                {
                    b.Navigation("Hosts");
                });
#pragma warning restore 612, 618
        }
    }
}
